# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\App_WebCam.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_App_WebCam(object):
    def setupUi(self, App_WebCam):
        App_WebCam.setObjectName("App_WebCam")
        App_WebCam.resize(946, 459)
        self.centralwidget = QtWidgets.QWidget(App_WebCam)
        self.centralwidget.setObjectName("centralwidget")
        self.Webcam_label = QtWidgets.QLabel(self.centralwidget)
        self.Webcam_label.setGeometry(QtCore.QRect(10, 10, 640, 360))
        self.Webcam_label.setFrameShape(QtWidgets.QFrame.Box)
        self.Webcam_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Webcam_label.setLineWidth(7)
        self.Webcam_label.setText("")
        self.Webcam_label.setObjectName("Webcam_label")
        self.text_view = QtWidgets.QTextEdit(self.centralwidget)
        self.text_view.setGeometry(QtCore.QRect(660, 10, 271, 401))
        self.text_view.setObjectName("text_view")
        App_WebCam.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(App_WebCam)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 946, 21))
        self.menubar.setObjectName("menubar")
        App_WebCam.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(App_WebCam)
        self.statusbar.setObjectName("statusbar")
        App_WebCam.setStatusBar(self.statusbar)

        self.retranslateUi(App_WebCam)
        QtCore.QMetaObject.connectSlotsByName(App_WebCam)

    def retranslateUi(self, App_WebCam):
        _translate = QtCore.QCoreApplication.translate
        App_WebCam.setWindowTitle(_translate("App_WebCam", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    App_WebCam = QtWidgets.QMainWindow()
    ui = Ui_App_WebCam()
    ui.setupUi(App_WebCam)
    App_WebCam.show()
    sys.exit(app.exec_())
