# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Main_testui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1060, 540)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 321, 27))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(self.layoutWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.Button_Setting = QtWidgets.QPushButton(self.splitter)
        self.Button_Setting.setObjectName("Button_Setting")
        self.Button_Mouse = QtWidgets.QPushButton(self.splitter)
        self.Button_Mouse.setObjectName("Button_Mouse")
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        self.Button_Keyboard = QtWidgets.QPushButton(self.layoutWidget)
        self.Button_Keyboard.setObjectName("Button_Keyboard")
        self.gridLayout.addWidget(self.Button_Keyboard, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.Button_Exit = QtWidgets.QPushButton(self.layoutWidget)
        self.Button_Exit.setObjectName("Button_Exit")
        self.gridLayout_2.addWidget(self.Button_Exit, 0, 1, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(490, 90, 158, 25))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Button_Dev_Mode = QtWidgets.QPushButton(self.layoutWidget1)
        self.Button_Dev_Mode.setObjectName("Button_Dev_Mode")
        self.gridLayout_3.addWidget(self.Button_Dev_Mode, 0, 0, 1, 1)
        self.Button_Release_Mode = QtWidgets.QPushButton(self.layoutWidget1)
        self.Button_Release_Mode.setObjectName("Button_Release_Mode")
        self.gridLayout_3.addWidget(self.Button_Release_Mode, 0, 1, 1, 1)
        self.list_view = QtWidgets.QListView(self.centralwidget)
        self.list_view.setGeometry(QtCore.QRect(660, 50, 381, 441))
        self.list_view.setAutoFillBackground(False)
        self.list_view.setObjectName("list_view")
        self.Webcam_label = QtWidgets.QLabel(self.centralwidget)
        self.Webcam_label.setGeometry(QtCore.QRect(10, 130, 640, 360))
        self.Webcam_label.setFrameShape(QtWidgets.QFrame.Box)
        self.Webcam_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Webcam_label.setLineWidth(7)
        self.Webcam_label.setText("")
        self.Webcam_label.setObjectName("Webcam_label")
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 90, 158, 25))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.Button_WebCam_Start = QtWidgets.QPushButton(self.layoutWidget2)
        self.Button_WebCam_Start.setObjectName("Button_WebCam_Start")
        self.gridLayout_4.addWidget(self.Button_WebCam_Start, 0, 0, 1, 1)
        self.Button_WebCam_Stop = QtWidgets.QPushButton(self.layoutWidget2)
        self.Button_WebCam_Stop.setObjectName("Button_WebCam_Stop")
        self.gridLayout_4.addWidget(self.Button_WebCam_Stop, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1060, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button_Setting.setText(_translate("MainWindow", "Setting"))
        self.Button_Mouse.setText(_translate("MainWindow", "Mouse"))
        self.Button_Keyboard.setText(_translate("MainWindow", "Keyboard"))
        self.Button_Exit.setText(_translate("MainWindow", "Exit"))
        self.Button_Dev_Mode.setText(_translate("MainWindow", "개발 모드"))
        self.Button_Release_Mode.setText(_translate("MainWindow", "릴리즈 모드"))
        self.Button_WebCam_Start.setText(_translate("MainWindow", "웹캠 테스트"))
        self.Button_WebCam_Stop.setText(_translate("MainWindow", "웹캠 중단"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
